on:
    push:

jobs: 
    test: 
        runs-on: ubuntu_latest
        steps: 
            - uses: actions/checkout@v4
            - name: setup python 
              uses: actions/setup-python@v5
              with:
                python-version: 3.12
            - name: Install Requirements
              run: pip install -r requirements.txt

            - name: Run tests 
              run: pytest
    build-and-push:
        needs: [test]
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - name: Build and push docker container 
              run:
                docker build -t farahmo99/demo_flask_app .
                echo ${{ secrets.NEW_SECRET}} | docker login -u farahmo99 --password-stdin 
                docker push farahmo99/demo_flask_app


        
